import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import DataContext from "../contexts/DataContext"
import AppContext from "../contexts/AppContext"
import UnitContext from "../contexts/UnitContext"
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased bg-[#071127] px-10 pt-20 pb-10`}
      >
        <AppContext >
          <DataContext>
            <UnitContext>
              {children}
            </UnitContext>
          </DataContext>
        </AppContext>


      </body>
    </html>
  );
}
