import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppData from "@/contexts/AppData";
import ModalData from "@/contexts/ModalData";
import State from "@/contexts/State";
import Search from "@/contexts/Search";
import Tag from "@/contexts/Tag";
import { ClerkProvider } from '@clerk/nextjs'



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} `}>
      <body className="bg-gray-100 text-gray-900">
        <AppData>
          <ModalData>
            <State>
              <Tag>
                <Search>{children}</Search>
              </Tag>
            </State>
          </ModalData>
        </AppData>
      </body>
    </html>
    </ClerkProvider>
  );
}
