import { Inter, Fraunces, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import AppData from "@/contexts/AppData";
import ModalData from "@/contexts/ModalData";
import State from "@/contexts/State";
import Search from "@/contexts/Search";
import Tag from "@/contexts/Tag";
import { ClerkProvider } from '@clerk/nextjs'



const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const fraunces = Fraunces({
  variable: "--font-fraunces",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en" className={`${inter.variable} ${fraunces.variable} ${jetbrainsMono.variable}`}>
      <body className="bg-parchment text-ink font-sans">
        <AppData>
          <ModalData>
            <State>
              <Tag>
                <Search>{children}</Search>
              </Tag>
            </State>
          </ModalData>
        </AppData>
      </body>
    </html>
    </ClerkProvider>
  );
}